### ISSUE TITLE
Error on provision

### ISSUE THREAD

**Issue by kucrut** [Chassis/Chassis_Elasticsearch#11]
```
[vagrant] ==> default: Running Puppet with development.pp...
[vagrant] ==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class chassis-elasticsearch at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:19 on node vagrant.local
[vagrant] ==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class chassis-elasticsearch at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:19 on node vagrant.local
```

1. What operating system do you use?
    MacOS

2. What version of Vagrant are you running?
    2.2.5

3. Are you using VirtualBox or VMWare and which version are you using?
    VirtualBox

4. Do you have a custom YAML file?
    No.

5. Do you have any Chassis other extensions installed? If so, what are they?
    No.

**Comment by BronsonQuick** [comment]
Looks like I was too speedy to merge my Bionic Beaver changes into this extension. For now you'll need to rename your `chassis-elasticsearch` folder to `chassis_elasticsearch`. Once https://github.com/Chassis/Chassis/pull/658 is merged this will be automated. For now I need to fix up the readme instructions for cloning the extension.
