### ISSUE TITLE
Getting provision error 'Syntax error at 'String'; expected ')''

### ISSUE THREAD

**Issue by santoshgudlaSI** [Chassis/Chassis_Elasticsearch#18]
1. What operating system do you use?

> `Ubuntu 18.04`

2. What version of Vagrant are you running?

> `Vagrant 2.0.2`

3. Are you using VirtualBox or VMWare and which version are you using?

> Virtualbox 5.2.8

4. Do you have a custom YAML file? If so, what does it contain?
 ```extensions:
    - chassis/cavalcade
    - chassis/mailhog
    - chassis/memcache
    - chassis/sequelpro
    - chassis/tester
    - chassis/xdebug
    - chassis/chassis_elasticsearch
    - roborourke/chassis-openssl
```
When reprovisioning after adding an extensions, I'm getting this error

`Error: Syntax error at 'String'; expected ')' at /vagrant/extensions/chassis_elasticsearch/modules/java/manifests/init.pp:39 on node vagrant.local`

**Comment by BronsonQuick** [comment]
Hey @santoshgudlaSI, I've just provisioned a new Chassis instance from scratch with these extensions and it's working fine for me.

My guess is that you haven't got up to date submodules in `chassis_elasticsearch` can you please try running `cd /extensions/chassis_elasticsearch` then `git submodule update --init` and then `vagrant provision` and see if that fixes your issue? Thanks!

**Comment by santoshgudlaSI** [comment]
@BronsonQuick Thanks for the reply.

But no luck, still the same error.
you have any more suggestions?

Thanks.

**Comment by BronsonQuick** [comment]
Can you check if the master branch of Chassis is up to date? Either that or the Elasticsearch extension isn't up to date.

**Comment by santoshgudlaSI** [comment]
Both are up to date, still, I am getting the above error

**Comment by BronsonQuick** [comment]
Hmm. Can you check that you're using the latest base box of Chassis? It should be `3.0.2` I think any version higher than 3 should be fine though.

**Comment by santoshgudlaSI** [comment]
@BronsonQuick it's fixed now, I have the latest box of chassis.

Thanks for your support
