### ISSUE TITLE
Elastic Search Install is broken

### ISSUE THREAD

**Issue by nprasath002** [Chassis/Chassis_Elasticsearch#29]
Steps to reproduce
1. Install chassis
2. Checkout this module under extensions directory
3. Run `vagrant provision`

<img width="1790" alt="Screenshot 2021-01-06 at 11 48 03" src="https://user-images.githubusercontent.com/581008/103735910-157d4a80-5015-11eb-9c10-eb91466f98c7.png">

**Comment by BronsonQuick** [comment]
@nprasath002 Can you please try it out on this commit: https://github.com/Chassis/Chassis_Elasticsearch/commit/1f196f1a22f05bc7e1996c7940af770478914dff If that works then I'll revert https://github.com/Chassis/Chassis_Elasticsearch/pull/28

**Comment by nprasath002** [comment]
I tried that and got a different error now

<img width="1792" alt="Screenshot 2021-01-06 at 13 37 22" src="https://user-images.githubusercontent.com/581008/103744793-62b4e880-5024-11eb-82e9-07390c4f9f7b.png">

**Comment by BronsonQuick** [comment]
It's been a while since I've used this extension but I think this has been fixed: 
<img width="1522" alt="fixed" src="https://user-images.githubusercontent.com/1377956/107510813-4f330980-6bf0-11eb-8db5-a3d19de22876.png">

**Comment by nprasath002** [comment]
Yep. My recent install was successful
